name: eagles-postman-newman

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  run-postman-tests:
    name: Quality Eagles Postman Newman Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Newman and Node version
        run: |
          newman --version
          node --version

      - name: Install newman-reporter-htmlextra
        run: |
          sudo npm install -g newman-reporter-htmlextra

      - name: Run Collection Ítalo
        run: |
          newman run ./Italo-QualityEagles.postman_collection.json \
          --globals ./Italo-QualityEagles.postman_globals.json \
          --delay-request 2 \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export ./result/Report_Collection_Italo.html

      - name: Create result directory
        run: mkdir -p ./result

      - name: Run Collection Jamile
        run: |
          newman run ./Jamile-QualityEagles.postman_collection.json \
          --globals ./Jamile-QualityEagles.postman_globals.json \
          --delay-request 2 \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export ./result/Report_Collection_Jamile.html

      - name: Archive Reports
        run: |
          zip -r ./result/reports.zip ./result/*.html

      - name: Upload Archive
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: ./result/reports.zip
  run-insomnia-tests:
    name: Quality Eagles Insomnia Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print working directory
        run: pwd

      # - name: Change to correct directory
      #   run: cd /home/runner/work/eagles-postman-newman

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Setup inso
        # You may pin to the exact commit or the version.
        uses: Kong/setup-inso@cf1bf7b12e5d0092399c79025c09eba54d8182f7
        # uses: Kong/setup-inso@b724fdcc07124e43ba013363f4ecb07c8ad56ec8
        # uses: Kong/setup-inso@v1
        with:
          # The version of inso to install
          inso-version: 10.1.1
            # The compression algorithm to use. One of: [gzip, bzip]
          compression: gzip
        # Add a wrapper script to make stdout, stderr and errorcode available as outputs
        # wrapper: # optional, default is false

      - name: Print inso version
        run: inso --version

      - name: Verify directory
        run: |
          ls -la /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data

      - name: Enter into
        run: cd /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data

      - name: Change permission
        run: chmod 777 /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data/*

      - name: Verify directory again
        run: |
          ls -la /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data

      - name: Verify relative path
        run: |
          ls -la ./insomnia-data

      - name: Verify CI dir
        run: |
          ls -la /home/runner/work/

      - name: Verify CI app dir
        run: |
          ls -la /home/runner/work/eagles-postman-newman/

      - name: Verify CI app data
        run: |
          ls -la /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data

      # - name: Lint
      #   run: inso lint spec "Tadeu-QualityEagles-Collection" -w ./../../../../../.insomnia --ci

        # wrk_90837a2c267749558521976f34c2b06b (env - resources.id (workspace))
        # env_72323603fe964ca5a001487d84200402 (env - resources.id (environment))
      # - name: Run script 1
      #   run: inso run test wrk_90837a2c267749558521976f34c2b06b --env env_72323603fe964ca5a001487d84200402 --workingDir /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data --verbose --ci
      # - name: Run script 2
      #   run: inso run collection wrk_90837a2c267749558521976f34c2b06b --env env_72323603fe964ca5a001487d84200402 --workingDir /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data --verbose --ci

        # req_6ee84fa004a44a0b9daa641813baac6a (col - resources.id (workspace))
        # wrk_90837a2c267749558521976f34c2b06b (env - resources.id (workspace))
      # - name: Run script 3
      #   run: inso run test req_6ee84fa004a44a0b9daa641813baac6a --env wrk_90837a2c267749558521976f34c2b06b --workingDir /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data --verbose --ci
      # - name: Run script 4
      #   run: inso run collection req_6ee84fa004a44a0b9daa641813baac6a --env wrk_90837a2c267749558521976f34c2b06b --workingDir /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data --verbose --ci

        # req_6ee84fa004a44a0b9daa641813baac6a (col - resources.id (workspace))
        # env_72323603fe964ca5a001487d84200402 (env - resources.id (environment))
      # - name: Run script 5
      #   run: inso run test req_6ee84fa004a44a0b9daa641813baac6a --env env_72323603fe964ca5a001487d84200402 --workingDir /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data --verbose --ci
      # - name: Run script 6
      #   run: inso run collection req_6ee84fa004a44a0b9daa641813baac6a --env env_72323603fe964ca5a001487d84200402 --workingDir /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data --verbose --ci

        # req_6ee84fa004a44a0b9daa641813baac6a (col - resources.id (workspace))
        # env_72323603fe964ca5a001487d84200402 (env - resources.id (environment))
      # - name: Run script 7
      #   run: inso run collection req_6ee84fa004a44a0b9daa641813baac6a --env env_72323603fe964ca5a001487d84200402 --workingDir /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data --verbose --ci
      - name: Run script 8
        run: inso run test wrk_e1e1ad06132e4625bddace0569de4612 --env env_2b2ddd0cd9598ca8550efea5f2b0771fa6ea0c29 --workingDir /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data --verbose --ci
      # - name: Run script 9
      #   run: inso run collection wrk_e1e1ad06132e4625bddace0569de4612 --env env_2b2ddd0cd9598ca8550efea5f2b0771fa6ea0c29 --workingDir /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data --verbose --ci



        # run: inso run test wrk_90837a2c267749558521976f34c2b06b --env env_72323603fe964ca5a001487d84200402 --workingDir /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data --verbose --ci
        # run: inso run test Tadeu-QualityEagles-Collection.json --env Tadeu-QualityEagles-Globals.json --workingDir ./insomnia-data --verbose --ci

        # working-directory: /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data
        # run: inso run collection "Tadeu-QualityEagles-Collection" --env "Tadeu-QualityEagles-Globals" --workingDir /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data --verbose --ci













      # - run: echo '${{ toJson(steps.inso_version.outputs) }}'

      # - name: Set up inso
      #   uses: kong/setup-inso@v1
      #   with:
      #     inso-version: 10.3.1
      # - run: inso --version
      
      # - uses: kong/setup-inso@v1
      #   with:
      #     # inso-version: 10.3.1
      #     inso-version: 2.4.0
      #     compression: gzip
      # - run: inso --version
      #   id: inso_version
      # - run: echo '${{ toJson(steps.inso_version.outputs) }}'
      # # - name: Lint
      #   # run: inso lint spec Tadeu-QualityEagles-Collection_Insomnia_2025-02-24.json --ci
      # - name: Run test suites
      #   run: inso run collection Tadeu-QualityEagles-Collection_Insomnia_2025-02-24.json -e Tadeu-QualityEagles-Globals_Insomnia_2025-02-24.json --ci
